version: '3'

services:
  mysql:
    image: mysql/mysql-server:latest
    #    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_HOST=%
    volumes:
      - /data/mysql
  movie-ratings:
    restart: on-failure
    image: movie-ratings-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8082:8082
